import { Category, Product, Deal, BusinessSettings, DiningTable } from '@/types';

export const initialCategories: Category[] = [
  { id: 'deals', nameEn: 'Student Deals', nameUr: 'سٹوڈنٹ ڈیلز', iconName: 'Flame', order: 1 },
  { id: 'shawarma', nameEn: 'Shawarma', nameUr: 'شوارما', iconName: 'Wrap', order: 2 },
  { id: 'platters-rolls', nameEn: 'Platters & Rolls', nameUr: 'پلیٹر اور رول', iconName: 'Utensils', order: 3 },
  { id: 'zinger-burgers', nameEn: 'Zinger Burgers', nameUr: 'زنگر برگر', iconName: 'Sandwich', order: 4 },
  { id: 'shami-burgers', nameEn: 'Shami Burgers', nameUr: 'شامی برگر', iconName: 'Sandwich', order: 5 },
  { id: 'chicken-burgers', nameEn: 'Chicken Burgers', nameUr: 'چکن برگر', iconName: 'Sandwich', order: 6 },
  { id: 'shappatta-rolls', nameEn: 'Shappatta Roll', nameUr: 'شپٹہ رول', iconName: 'Utensils', order: 7 },
  { id: 'paratha-rolls', nameEn: 'Paratha Rolls', nameUr: 'پراٹھا رول', iconName: 'Utensils', order: 8 },
  { id: 'fries', nameEn: 'Fries', nameUr: 'فرائز', iconName: 'Utensils', order: 9 },
  { id: 'sandwiches', nameEn: 'Sandwiches', nameUr: 'سینڈوچ', iconName: 'Layers', order: 10 },
  { id: 'soups', nameEn: 'Soup', nameUr: 'سوپ', iconName: 'Utensils', order: 11 },
  { id: 'addons', nameEn: 'Extras & Add-ons', nameUr: 'ایکسٹرا', iconName: 'PlusCircle', order: 12 },
];

const previousProducts: Product[] = [
  // SHAWARMA (Right top column)
  {
    id: 'chicken-shawarma-s',
    nameEn: 'Regular Shawarma',
    nameUr: 'ریگولر شوارما',
    categoryId: 'shawarma',
    price: 180,
    descriptionEn: 'Tender spiced shredded chicken wrapped in warm pita with authentic garlic sauce and crisp vegetables.',
    descriptionUr: 'تازہ چکن، روایتی ساس اور کرسپی سلاد کے ساتھ گرم شوارما بریڈ میں۔',
    image: '/images/products/chicken-shawarma-s.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '180/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Top - Shawarma',
  },
  {
    id: 'student-special-shawarma',
    nameEn: 'Especial Shawarma',
    nameUr: 'اسپیشل شوارما',
    categoryId: 'shawarma',
    price: 250,
    descriptionEn: 'The signature chef loaded shawarma with double chicken, cheese blend, and secret Student house sauces.',
    descriptionUr: 'ہمارا خصوصی شاہکار شوارما، ڈبل چکن، چیز اور اسپیشل ساسز سے تیار۔',
    image: '/images/products/student-special-shawarma.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '250/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Top - Shawarma',
  },
  {
    id: 'zinger-shawarma-m',
    nameEn: 'Zinger Shawarma',
    nameUr: 'زنگر شوارما',
    categoryId: 'shawarma',
    price: 300,
    descriptionEn: 'Crunchy golden-fried zinger strips wrapped in soft shawarma bread with secret garlic mayo.',
    descriptionUr: 'کرسپی گولڈن زنگر چکن اسٹرپس نرم شوارما بریڈ میں۔',
    image: '/images/products/zinger-shawarma-m.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '300/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Top - Shawarma',
  },

  // PLATTER (Right bottom column)
  {
    id: 'chicken-platter-shawarma',
    nameEn: 'Platter Shawarma',
    nameUr: 'پلیٹر شوارما',
    categoryId: 'platters-rolls',
    price: 450,
    descriptionEn: 'Generous platter of succulent shawarma chicken served open with sliced pita bread, fries, garlic dip, and crisp pickle salad.',
    descriptionUr: 'کھلی پلیٹ میں سجا چکن شوارما، فرائز، کٹی ہوئی پیٹا بریڈ، ساس اور سلاد کے ساتھ۔',
    image: '/images/products/chicken-platter-shawarma.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '450/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Bottom - Platters & Paratha',
  },

  // BURGERS (Left top column)
  {
    id: 'zinger-burger',
    nameEn: 'Zinger Burger',
    nameUr: 'زنگر برگر',
    categoryId: 'burgers',
    price: 280,
    descriptionEn: 'Crispy fried spicy chicken breast fillet topped with fresh lettuce and rich creamy mayo in a toasted sesame bun.',
    descriptionUr: 'کرسپی فرائیڈ چکن فلے، تازہ سلاد پتہ اور مایونیز تل والے برگر بن میں۔',
    image: '/images/products/zinger-burger.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '280/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Top - Burgers',
  },
  {
    id: 'chicken-burger',
    nameEn: 'Chicken Burger',
    nameUr: 'چکن برگر',
    categoryId: 'burgers',
    price: 230,
    descriptionEn: 'Seasoned minced chicken patty grilled to perfection with onions and house sauce.',
    descriptionUr: 'لذیذ گرلڈ چکن پیٹی برگر روایتی مصالحہ دار ساس کے ساتھ۔',
    image: '/images/products/chicken-burger.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '230/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Top - Burgers',
  },
  {
    id: 'student-special-chicken-burger',
    nameEn: 'Student Special Chicken Burger',
    nameUr: 'سٹوڈنٹ اسپیشل چکن برگر',
    categoryId: 'burgers',
    price: 260,
    descriptionEn: 'Our signature loaded chicken burger with double sauce, fried egg/cheese layering, and extra crispiness.',
    descriptionUr: 'سٹوڈنٹ فاسٹ فوڈ کا اسپیشل چکن برگر، خاص ذائقہ اور مصالحہ۔',
    image: '/images/products/student-special-chicken-burger.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '260/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Top - Burgers',
  },
  {
    id: 'chicken-tikka-burger',
    nameEn: 'Chicken Tikka Burger',
    nameUr: 'چکن تکہ برگر',
    categoryId: 'burgers',
    price: 250,
    descriptionEn: 'Chargrilled BBQ chicken tikka chunks packed inside a soft toasted bun with spicy yogurt sauce.',
    descriptionUr: 'باربی کیو چکن تکہ کا لاجواب ذائقہ برگر بن میں۔',
    image: '/images/products/chicken-tikka-burger.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '250/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Top - Burgers',
  },
  {
    id: 'anda-shami-burger',
    nameEn: 'Anda Shami Burger',
    nameUr: 'انڈہ شامی برگر',
    categoryId: 'burgers',
    price: 150,
    descriptionEn: 'Authentic Pakistani street-style burger featuring a seasoned shami patty topped with a fresh fried egg and onion rings.',
    descriptionUr: 'روایتی دیسی شامی کباب اور تلے ہوئے انڈے کا مشہور لاہوری برگر۔',
    image: '/images/products/anda-shami-burger.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '150/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Top - Burgers',
  },

  // CHICKEN & SNACKS (Left middle column)
  {
    id: 'chicken-drumstick',
    nameEn: 'Chicken Drumstick (1 pc)',
    nameUr: 'چکن ڈرم اسٹک',
    categoryId: 'chicken-snacks',
    price: 120,
    descriptionEn: 'Golden crispy southern-fried chicken drumstick, crunchy on the outside, juicy on the inside.',
    descriptionUr: 'کرسپی فرائیڈ چکن ڈرم اسٹک (1 عدد)۔',
    image: '/images/products/chicken-drumstick.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '120/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Middle - Snacks',
  },
  {
    id: 'zinger-wrap',
    nameEn: 'Zinger Wrap',
    nameUr: 'زنگر Wrap',
    categoryId: 'chicken-snacks',
    price: 350,
    descriptionEn: 'Crispy zinger chicken strips, lettuce, and creamy pepper sauce wrapped tightly in a toasted flour tortilla.',
    descriptionUr: 'کرنچی زنگر چکن اور سپائسی مایو ٹارٹیلا ریپ میں۔',
    image: '/images/products/zinger-wrap.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '350/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Middle - Snacks',
  },
  {
    id: 'wings-5-pcs',
    nameEn: 'Wings (5 Pieces)',
    nameUr: 'ونگز پیس 5',
    categoryId: 'chicken-snacks',
    price: 300,
    descriptionEn: 'Five pieces of crispy golden breaded chicken wings served with dipping sauce.',
    descriptionUr: 'کرسپی فرائیڈ چکن ونگز 5 عدد۔',
    image: '/images/products/wings-5-pcs.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '300/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Middle - Snacks',
  },
  {
    id: 'wings-10-pcs',
    nameEn: 'Wings (10 Pieces)',
    nameUr: 'ونگز پیس 10',
    categoryId: 'chicken-snacks',
    price: 590,
    descriptionEn: 'Ten pieces of golden crispy chicken wings, perfect for sharing.',
    descriptionUr: 'کرسپی فرائیڈ چکن ونگز 10 عدد، فیملی اور دوستوں کے لیے۔',
    image: '/images/products/wings-10-pcs.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '590/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Middle - Snacks',
  },

  // SANDWICHES (Left 3rd column)
  {
    id: 'club-sandwich',
    nameEn: 'Club Sandwich',
    nameUr: 'کلب سینڈوچ',
    categoryId: 'sandwiches',
    price: 270,
    descriptionEn: 'Classic triple-layered toasted sandwich loaded with shredded chicken, boiled egg slices, cucumber, and creamy spread.',
    descriptionUr: 'کلاسک تھری لیئر ٹوسٹڈ کلب سینڈوچ چکن، انڈہ اور مایو کے ساتھ۔',
    image: '/images/products/club-sandwich.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '270/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left 3rd - Sandwiches',
  },
  {
    id: 'chicken-tikka-sandwich',
    nameEn: 'Chicken Tikka Sandwich',
    nameUr: 'چکن تکہ سینڈوچ',
    categoryId: 'sandwiches',
    price: 290,
    descriptionEn: 'Toasted golden bread sandwiches stuffed with smoky spiced chicken tikka pieces and tangy sauce.',
    descriptionUr: 'باربی کیو چکن تکہ سے بھرا گرلڈ ٹوسٹڈ سینڈوچ۔',
    image: '/images/products/chicken-tikka-sandwich.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '290/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left 3rd - Sandwiches',
  },
  {
    id: 'zinger-sandwich',
    nameEn: 'Zinger Sandwich',
    nameUr: 'زنگر سینڈوچ',
    categoryId: 'sandwiches',
    price: 300,
    descriptionEn: 'Crispy fried zinger chicken fillet nestled between toasted bread slices with crisp lettuce and sauce.',
    descriptionUr: 'کرسپی فرائیڈ زنگر چکن اور مایونیز سینڈوچ۔',
    image: '/images/products/zinger-sandwich.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '300/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left 3rd - Sandwiches',
  },
  {
    id: 'student-special-sandwich',
    nameEn: 'Student Special Sandwich',
    nameUr: 'سٹوڈنٹ اسپیشل سینڈوچ',
    categoryId: 'sandwiches',
    price: 350,
    descriptionEn: 'Deluxe loaded sandwich with double meat filling, melted cheese layer, and secret house seasoning.',
    descriptionUr: 'سٹوڈنٹ کا خاص سینڈوچ، ڈبل چکن فلنگ اور چیز سے بھرپور۔',
    image: '/images/products/student-special-sandwich.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '350/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left 3rd - Sandwiches',
  },

  // EXTRAS & ADD-ONS (Left bottom column)
  {
    id: 'cheese-slice',
    nameEn: 'Cheese Slice',
    nameUr: 'چیز سلائس',
    categoryId: 'addons',
    price: 60,
    descriptionEn: 'Add an extra melted cheddar cheese slice to your shawarma, burger, or sandwich.',
    descriptionUr: 'شوارما یا برگر کے لیے اضافی چیز سلائس۔',
    image: '/images/products/cheese-slice.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '60/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Bottom - Extras',
  },
  {
    id: 'extra-mayo',
    nameEn: 'Extra Mayonnaise',
    nameUr: 'ایکسٹرا مایونیز',
    categoryId: 'addons',
    price: 30,
    descriptionEn: 'A cup of rich, creamy house garlic mayonnaise dip.',
    descriptionUr: 'اضافی گھریلو گارلک مایونیز ساس۔',
    image: '/images/products/extra-mayo.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '30/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Bottom - Extras',
  },
  {
    id: 'extra-bread',
    nameEn: 'Extra Bread / Pita',
    nameUr: 'ایکسٹرا بریڈ',
    categoryId: 'addons',
    price: 30,
    descriptionEn: 'An extra piece of warm, freshly made shawarma pita bread.',
    descriptionUr: 'اضافی تازہ شوارما پیٹا بریڈ۔',
    image: '/images/products/extra-bread.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '30/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Bottom - Extras',
  },
];

const previousProductsById = new Map(previousProducts.map((product) => [product.id, product]));

function menuProduct(
  id: string,
  nameEn: string,
  nameUr: string,
  categoryId: string,
  price: number,
  image: string,
  descriptionEn: string,
  originalMenuSection: string
): Product {
  const previous = previousProductsById.get(id);
  return {
    id,
    nameEn,
    nameUr,
    categoryId,
    price,
    descriptionEn,
    descriptionUr: previous?.descriptionUr ?? nameUr,
    image: previous?.image ?? image,
    isAvailable: previous?.isAvailable ?? true,
    isFeatured: previous?.isFeatured ?? false,
    originalPriceFormat: `${price}/- روپے`,
    verifiedFromMenu: true,
    originalMenuSection,
  };
}

export const initialProducts: Product[] = [
  menuProduct('chicken-shawarma-s', 'Regular Shawarma', 'ریگولر شوارما', 'shawarma', 180, '/images/products/chicken-shawarma-s.webp', 'Regular chicken shawarma wrapped in warm pita.', 'Shawarma'),
  menuProduct('student-special-shawarma', 'Especial Shawarma', 'اسپیشل شوارما', 'shawarma', 250, '/images/products/student-special-shawarma.webp', 'Student special shawarma with chicken and house sauces.', 'Shawarma'),
  menuProduct('zinger-shawarma-m', 'Zinger Shawarma', 'زنگر شوارما', 'shawarma', 300, '/images/products/zinger-shawarma-m.webp', 'Crispy zinger chicken wrapped in shawarma bread.', 'Shawarma'),
  menuProduct('chicken-platter-shawarma', 'Platter Shawarma', 'پلیٹر شوارما', 'platters-rolls', 450, '/images/products/chicken-platter-shawarma.webp', 'Chicken shawarma platter.', 'Platter & Shappatta Roll'),

  menuProduct('zinger-burger', 'Zinger Burger', 'زنگر برگر', 'zinger-burgers', 300, '/images/products/zinger-burger.webp', 'Crispy zinger chicken burger.', 'Zinger Burgers'),
  menuProduct('zinger-burger-fries', 'Zinger Burger + Fries', 'زنگر برگر اور فرائز', 'zinger-burgers', 350, '/images/products/zinger-burger.webp', 'Zinger burger served with fries.', 'Zinger Burgers'),
  menuProduct('zinger-lapeta-burger', 'Zinger Lapeta Burger', 'زنگر لپیٹا برگر', 'zinger-burgers', 350, '/images/products/zinger-burger.webp', 'Zinger chicken lapeta burger.', 'Zinger Burgers'),
  menuProduct('zinger-double-tekar-fries', 'Zinger Double Tekar + Fries', 'زنگر ڈبل ٹیکر اور فرائز', 'zinger-burgers', 600, '/images/products/zinger-burger.webp', 'Zinger double tekar served with fries.', 'Zinger Burgers'),
  menuProduct('zinger-piece', 'Zinger Piece', 'زنگر پیس', 'zinger-burgers', 250, '/images/products/zinger-burger.webp', 'Crispy zinger chicken piece.', 'Zinger Burgers'),

  menuProduct('shami-burger', 'Shami Burger', 'شامی برگر', 'shami-burgers', 150, '/images/products/anda-shami-burger.webp', 'Shami kebab burger.', 'Shami Burgers'),
  menuProduct('shami-double-anda-burger', 'Shami Double Anda Burger', 'شامی ڈبل انڈہ برگر', 'shami-burgers', 200, '/images/products/anda-shami-burger.webp', 'Shami burger with double egg.', 'Shami Burgers'),
  menuProduct('gol-shami-burger', 'Gol Shami Burger', 'گول شامی برگر', 'shami-burgers', 180, '/images/products/anda-shami-burger.webp', 'Gol shami burger.', 'Shami Burgers'),
  menuProduct('student-especial-lapeta-burger', 'Student Especial Lapeta Burger', 'سٹوڈنٹ اسپیشل لپیٹا برگر', 'shami-burgers', 250, '/images/products/student-special-chicken-burger.webp', 'Student especial lapeta burger.', 'Shami Burgers'),

  menuProduct('chicken-patty-burger', 'Chicken Patty Burger', 'چکن پیٹی برگر', 'chicken-burgers', 250, '/images/products/chicken-burger.webp', 'Chicken patty burger.', 'Chicken Burgers'),
  menuProduct('chicken-patty-burger-fries', 'Chicken Patty Burger + Fries', 'چکن پیٹی برگر اور فرائز', 'chicken-burgers', 300, '/images/products/chicken-burger.webp', 'Chicken patty burger served with fries.', 'Chicken Burgers'),
  menuProduct('chicken-burger', 'Chicken Burger', 'چکن برگر', 'chicken-burgers', 350, '/images/products/chicken-burger.webp', 'Chicken burger.', 'Chicken Burgers'),

  menuProduct('shappatta-roll', 'Shappatta Roll', 'شپٹہ رول', 'shappatta-rolls', 500, '/images/products/special-paratha-roll.webp', 'Shappatta roll.', 'Shappatta Roll'),
  menuProduct('malai-boti-sandwich', 'Malai Boti Sandwich', 'ملائی بوٹی سینڈوچ', 'shappatta-rolls', 500, '/images/products/chicken-tikka-sandwich.webp', 'Malai boti sandwich.', 'Shappatta Roll'),
  menuProduct('malai-boti-paratha-roll', 'Malai Boti Paratha Roll', 'ملائی بوٹی پراٹھا رول', 'shappatta-rolls', 400, '/images/products/special-paratha-roll.webp', 'Malai boti paratha roll.', 'Shappatta Roll'),
  menuProduct('tikka-shawarma', 'Tikka Shawarma', 'تکہ شوارما', 'shappatta-rolls', 300, '/images/products/chicken-tikka-shawarma.webp', 'Chicken tikka shawarma.', 'Shappatta Roll'),

  menuProduct('chicken-paratha-roll', 'Chicken Paratha Roll', 'چکن پراٹھا رول', 'paratha-rolls', 350, '/images/products/special-paratha-roll.webp', 'Chicken paratha roll.', 'Paratha Rolls'),
  menuProduct('zinger-paratha-roll', 'Zinger Paratha Roll', 'زنگر پراٹھا رول', 'paratha-rolls', 350, '/images/products/zinger-paratha-roll.webp', 'Crispy zinger chicken wrapped in paratha.', 'Paratha Rolls'),

  menuProduct('half-fries', 'Half Fries', 'ہاف فرائز', 'fries', 150, '/images/products/zinger-paratha-roll.webp', 'Half portion of fries.', 'Fries'),
  menuProduct('full-fries', 'Full Fries', 'فل فرائز', 'fries', 300, '/images/products/zinger-paratha-roll.webp', 'Full portion of fries.', 'Fries'),

  menuProduct('chicken-sandwich', 'Chicken Sandwich', 'چکن سینڈوچ', 'sandwiches', 400, '/images/products/student-special-sandwich.webp', 'Chicken sandwich.', 'Sandwiches'),
  menuProduct('club-sandwich', 'Club Sandwich', 'کلب سینڈوچ', 'sandwiches', 350, '/images/products/club-sandwich.webp', 'Classic layered club sandwich.', 'Sandwiches'),
  menuProduct('chicken-tikka-sandwich', 'Chicken Tikka Sandwich', 'چکن تکہ سینڈوچ', 'sandwiches', 400, '/images/products/chicken-tikka-sandwich.webp', 'Chicken tikka sandwich.', 'Sandwiches'),

  menuProduct('chicken-corn-soup', 'Chicken Corn Soup', 'چکن کارن سوپ', 'soups', 150, '/images/products/chicken-drumstick.webp', 'Chicken corn soup.', 'Soup'),
  menuProduct('hot-sour-soup', 'Hot & Sour Soup', 'ہاٹ اینڈ ساور سوپ', 'soups', 150, '/images/products/chicken-tikka-shawarma.webp', 'Hot and sour soup.', 'Soup'),

  menuProduct('extra-mayo', 'Extra Mayo (Small)', 'ایکسٹرا مایونیز (چھوٹی)', 'addons', 30, '/images/products/extra-mayo.webp', 'Small extra mayonnaise serving.', 'Extras & Add-ons'),
  menuProduct('extra-mayo-large', 'Extra Mayo (Large)', 'ایکسٹرا مایونیز (بڑی)', 'addons', 50, '/images/products/extra-mayo.webp', 'Large extra mayonnaise serving.', 'Extras & Add-ons'),
];

export const initialDeals: Deal[] = [
  {
    id: 'deal-1',
    dealNumber: 1,
    nameEn: 'Student Deal 1',
    nameUr: 'ڈیل 1',
    price: 400,
    originalPriceFormat: '400/-',
    image: '/images/products/zinger-burger.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Zinger Burger + French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Zinger Burger', nameUr: '1 زنگر برگر', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-2',
    dealNumber: 2,
    nameEn: 'Student Deal 2',
    nameUr: 'ڈیل 2',
    price: 350,
    originalPriceFormat: '350/-',
    image: '/images/products/student-special-chicken-burger.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Student Special Lapeta Burger + French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Student Special Lapeta Burger', nameUr: '1 سٹوڈنٹ اسپیشل لپیٹا برگر', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-3',
    dealNumber: 3,
    nameEn: 'Student Deal 3',
    nameUr: 'ڈیل 3',
    price: 280,
    originalPriceFormat: '280/-',
    image: '/images/deals/deal-3.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Regular Shawarma + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Regular Shawarma', nameUr: '1 ریگولر شوارما', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-4',
    dealNumber: 4,
    nameEn: 'Student Deal 4',
    nameUr: 'ڈیل 4',
    price: 350,
    originalPriceFormat: '350/-',
    image: '/images/deals/deal-4.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Special Shawarma + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Special Shawarma', nameUr: '1 اسپیشل شوارما', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-5',
    dealNumber: 5,
    nameEn: 'Student Deal 5',
    nameUr: 'ڈیل 5',
    price: 450,
    originalPriceFormat: '450/-',
    image: '/images/deals/deal-5.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Zinger Paratha Roll + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Zinger Paratha Roll', nameUr: '1 زنگر پراٹھا رول', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-6',
    dealNumber: 6,
    nameEn: 'Student Deal 6',
    nameUr: 'ڈیل 6',
    price: 400,
    originalPriceFormat: '400/-',
    image: '/images/deals/deal-6.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Zinger Shawarma + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Zinger Shawarma', nameUr: '1 زنگر شوارما', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-7',
    dealNumber: 7,
    nameEn: 'Student Deal 7',
    nameUr: 'ڈیل 7',
    price: 250,
    originalPriceFormat: '250/-',
    image: '/images/deals/deal-7.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Shami Burger + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Shami Burger', nameUr: '1 شامی برگر', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-8',
    dealNumber: 8,
    nameEn: 'Student Deal 8',
    nameUr: 'ڈیل 8',
    price: 350,
    originalPriceFormat: '350/-',
    image: '/images/deals/deal-8.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Chicken Patty Burger + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Chicken Patty Burger', nameUr: '1 چکن پیٹی برگر', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-9',
    dealNumber: 9,
    nameEn: 'Student Deal 9',
    nameUr: 'ڈیل 9',
    price: 400,
    originalPriceFormat: '400/-',
    image: '/images/deals/deal-9.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Chicken Burger + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Chicken Burger', nameUr: '1 چکن برگر', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-10',
    dealNumber: 10,
    nameEn: 'Student Deal 10',
    nameUr: 'ڈیل 10',
    price: 450,
    originalPriceFormat: '450/-',
    image: '/images/deals/deal-10.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Chicken Sandwich + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Chicken Sandwich', nameUr: '1 چکن سینڈوچ', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-11',
    dealNumber: 11,
    nameEn: 'Student Deal 11',
    nameUr: 'ڈیل 11',
    price: 400,
    originalPriceFormat: '400/-',
    image: '/images/deals/deal-11.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Club Sandwich + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Club Sandwich', nameUr: '1 کلب سینڈوچ', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-12',
    dealNumber: 12,
    nameEn: 'Student Deal 12',
    nameUr: 'ڈیل 12',
    price: 450,
    originalPriceFormat: '450/-',
    image: '/images/deals/deal-12.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Chicken Tikka Sandwich + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Chicken Tikka Sandwich', nameUr: '1 چکن تکہ سینڈوچ', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-13',
    dealNumber: 13,
    nameEn: 'Student Family Deal 13',
    nameUr: 'فیملی ڈیل 13',
    price: 1700,
    originalPriceFormat: '1700/-',
    image: '/images/deals/deal-13.webp',
    isAvailable: true,
    isFamilyDeal: true,
    verifiedFromMenu: true,
    descriptionEn: '5 Zinger Burgers + Half French Fries + 1.5 Liter Bottle',
    components: [
      { nameEn: 'Zinger Burger', nameUr: '5 زنگر برگر', quantity: 5 },
      { nameEn: 'Half French Fries', nameUr: 'ہاف فرائز', quantity: 1 },
      { nameEn: '1.5 Liter Cold Drink Bottle', nameUr: '1.5 لیٹر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-14',
    dealNumber: 14,
    nameEn: 'Student Deal 14 (Combo Feast)',
    nameUr: 'ڈیل 14',
    price: 850,
    originalPriceFormat: '850/-',
    image: '/images/deals/deal-14.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Regular Shawarma + 1 Shami Burger + 1 Zinger Burger + Half French Fries + 1 Liter Bottle',
    components: [
      { nameEn: 'Regular Shawarma', nameUr: '1 ریگولر شوارما', quantity: 1 },
      { nameEn: 'Shami Burger', nameUr: '1 شامی برگر', quantity: 1 },
      { nameEn: 'Zinger Burger', nameUr: '1 زنگر برگر', quantity: 1 },
      { nameEn: 'Half French Fries', nameUr: 'ہاف فرائز', quantity: 1 },
      { nameEn: '1 Liter Cold Drink Bottle', nameUr: '1 Liter بوتل', quantity: 1 },
    ],
  },
];

export const initialDiningTables: DiningTable[] = [
  { id: 'T01', label: 'Table 1', seats: 4, isActive: true },
  { id: 'T02', label: 'Table 2', seats: 4, isActive: true },
  { id: 'T03', label: 'Table 3', seats: 2, isActive: true },
  { id: 'T04', label: 'Table 4', seats: 6, isActive: true },
  { id: 'T05', label: 'Table 5', seats: 4, isActive: true },
  { id: 'T06', label: 'Table 6 (Family Hall)', seats: 8, isActive: true },
];

export const initialBusinessSettings: BusinessSettings = {
  restaurantName: 'Student Pizza & Fastfood',
  urduName: 'سٹوڈنٹ پیزا اینڈ فاسٹ فوڈ',
  tagline: 'Best Shawarma, Burgers & Student Deals in Lahore',
  phoneCandidate: '0309-4222283',
  whatsappNumberFormatted: '923094222283',
  isWhatsAppConfirmedByOwner: false, // Flagged pending owner confirmation per instructions
  address: 'Shalimar Link Road, Lahore, Pakistan',
  city: 'Lahore',
  googleMapsUrl: 'https://maps.google.com/?q=Shalimar+Link+Road+Lahore',
  facebookUrl: 'https://www.facebook.com/people/Student-pizza-Fastfood/100089295146903/',
  openingHoursFormatted: 'Hours will be updated soon',
  isSundayOff: false,
  deliveryCharges: 100, // PKR
  minimumOrder: 250, // PKR
  announcementText: 'Fresh & piping hot! Free fries dip on all orders above Rs. 1000. Dine-in & takeaway available.',
  isAnnouncementActive: true,
  currencySymbol: 'Rs.',
  dineInEnabled: true,
  takeawayEnabled: true,
  deliveryEnabled: true,
};
