import { Category, Product, Deal, BusinessSettings, DiningTable } from '@/types';

export const initialCategories: Category[] = [
  { id: 'deals', nameEn: 'Student Deals', nameUr: 'سٹوڈنٹ ڈیلز', iconName: 'Flame', order: 1 },
  { id: 'shawarma', nameEn: 'Shawarma', nameUr: 'شوارما', iconName: 'Wrap', order: 2 },
  { id: 'platters-rolls', nameEn: 'Platters & Parathas', nameUr: 'پلیٹر اور پراٹھا رول', iconName: 'Utensils', order: 3 },
  { id: 'burgers', nameEn: 'Burgers', nameUr: 'برگر', iconName: 'Sandwich', order: 4 },
  { id: 'chicken-snacks', nameEn: 'Crispy Chicken & Wings', nameUr: 'چکن اور اسنیکس', iconName: 'Drumstick', order: 5 },
  { id: 'sandwiches', nameEn: 'Sandwiches', nameUr: 'سینڈوچ', iconName: 'Layers', order: 6 },
  { id: 'addons', nameEn: 'Extras & Add-ons', nameUr: 'ایکسٹرا', iconName: 'PlusCircle', order: 7 },
];

export const initialProducts: Product[] = [
  // SHAWARMA (Right top column)
  {
    id: 'chicken-shawarma-s',
    nameEn: 'Chicken Shawarma (Small)',
    nameUr: 'چکن شوارما (S)',
    categoryId: 'shawarma',
    price: 130,
    descriptionEn: 'Tender spiced shredded chicken wrapped in warm pita with authentic garlic sauce and crisp vegetables.',
    descriptionUr: 'تازہ چکن، روایتی ساس اور کرسپی سلاد کے ساتھ گرم شوارما بریڈ میں۔',
    image: '/images/products/chicken-shawarma-s.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '130/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Top - Shawarma',
  },
  {
    id: 'chicken-shawarma-l',
    nameEn: 'Chicken Shawarma (Large)',
    nameUr: 'چکن شوارما (L)',
    categoryId: 'shawarma',
    price: 150,
    descriptionEn: 'Large portion of juicy spiced chicken shawarma with rich signature mayo-garlic dressing.',
    descriptionUr: 'بڑی سائز میں لذیذ چکن شوارما خصوصی مایو گارلک ساس کے ساتھ۔',
    image: '/images/products/chicken-shawarma-l.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '150/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Top - Shawarma',
  },
  {
    id: 'chicken-shawarma-jumbo',
    nameEn: 'Chicken Shawarma Jumbo',
    nameUr: 'چکن شوارما جمبو',
    categoryId: 'shawarma',
    price: 180,
    descriptionEn: 'Extra-stuffed jumbo chicken shawarma roll packed with premium seasoned chicken.',
    descriptionUr: 'جمبو سائز میں بھرپور چکن شوارما رول۔',
    image: '/images/products/chicken-shawarma-jumbo.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '180/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Top - Shawarma',
  },
  {
    id: 'chicken-tikka-shawarma',
    nameEn: 'Chicken Tikka Shawarma',
    nameUr: 'چکن تکہ شوارما',
    categoryId: 'shawarma',
    price: 200,
    descriptionEn: 'Charcoal-infused spicy chicken tikka pieces rolled in soft pita with mint and garlic sauces.',
    descriptionUr: 'دھواں دار باربی کیو چکن تکہ کی بوٹیاں مخصوص مصالحہ جات کے ساتھ۔',
    image: '/images/products/chicken-tikka-shawarma.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '200/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Top - Shawarma',
  },
  {
    id: 'chicken-achari-shawarma',
    nameEn: 'Chicken Achari Shawarma',
    nameUr: 'چکن اچاری شوارما',
    categoryId: 'shawarma',
    price: 180,
    descriptionEn: 'Zesty pickle-infused achari spiced chicken shawarma giving an authentic Pakistani punch.',
    descriptionUr: 'چٹپٹا اور تیکھا اچاری مصالحہ مکس چکن شوارما۔',
    image: '/images/products/chicken-achari-shawarma.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '180/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Top - Shawarma',
  },
  {
    id: 'student-special-shawarma',
    nameEn: 'Student Special Shawarma',
    nameUr: 'سٹوڈنٹ اسپیشل شوارما',
    categoryId: 'shawarma',
    price: 280,
    descriptionEn: 'The signature chef loaded shawarma with double chicken, cheese blend, and secret Student house sauces.',
    descriptionUr: 'ہمارا خصوصی شاہکار شوارما، ڈبل چکن، چیز اور اسپیشل ساسز سے تیار۔',
    image: '/images/products/student-special-shawarma.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '280/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Top - Shawarma',
  },
  {
    id: 'zinger-shawarma-m',
    nameEn: 'Zinger Shawarma (Medium)',
    nameUr: 'زنگر شوارما (M)',
    categoryId: 'shawarma',
    price: 200,
    descriptionEn: 'Crunchy golden-fried zinger strips wrapped in soft shawarma bread with secret garlic mayo.',
    descriptionUr: 'کرسپی گولڈن زنگر چکن اسٹرپس نرم شوارما بریڈ میں۔',
    image: '/images/products/zinger-shawarma-m.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '200/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Top - Shawarma',
  },
  {
    id: 'zinger-shawarma-jumbo',
    nameEn: 'Zinger Shawarma Jumbo',
    nameUr: 'زنگر شوارما جمبو',
    categoryId: 'shawarma',
    price: 250,
    descriptionEn: 'Super-sized jumbo zinger shawarma packed with extra crispy chicken strips and loaded mayo.',
    descriptionUr: 'بڑی سائز میں فل لوڈڈ کرسپی زنگر چکن شوارما۔',
    image: '/images/products/zinger-shawarma-jumbo.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '250/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Top - Shawarma',
  },

  // PLATTERS & PARATHA ROLLS (Right bottom column)
  {
    id: 'chicken-platter-shawarma',
    nameEn: 'Chicken Platter Shawarma',
    nameUr: 'چکن پلیٹر شوارما',
    categoryId: 'platters-rolls',
    price: 350,
    descriptionEn: 'Generous platter of succulent shawarma chicken served open with sliced pita bread, fries, garlic dip, and crisp pickle salad.',
    descriptionUr: 'کھلی پلیٹ میں سجا چکن شوارما، فرائز، کٹی ہوئی پیٹا بریڈ، ساس اور سلاد کے ساتھ۔',
    image: '/images/products/chicken-platter-shawarma.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '350/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Bottom - Platters & Paratha',
  },
  {
    id: 'zinger-platter-shawarma',
    nameEn: 'Zinger Platter Shawarma',
    nameUr: 'زنگر پلیٹر شوارما',
    categoryId: 'platters-rolls',
    price: 500,
    descriptionEn: 'Massive platter with golden crispy zinger fillets cut into bite-sized tenders, accompanied by golden fries, pita slices, and dipping sauces.',
    descriptionUr: 'بڑی پلیٹ میں کرسپی زنگر چکن فلے، فرائز، پیٹا بریڈ اور گارلک مایو ڈِپ۔',
    image: '/images/products/zinger-platter-shawarma.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '500/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Bottom - Platters & Paratha',
  },
  {
    id: 'zinger-paratha-roll',
    nameEn: 'Zinger Paratha Roll',
    nameUr: 'زنگر پراٹھا رول',
    categoryId: 'platters-rolls',
    price: 330,
    descriptionEn: 'Crispy fried zinger chicken rolled inside a hot, flaky, golden fried layered paratha with spicy sauce.',
    descriptionUr: 'خستہ و لذیذ تلواں پراٹھا میں لپٹا کرسپی زنگر چکن اور اسپیشل چٹنی۔',
    image: '/images/products/zinger-paratha-roll.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '330/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Bottom - Platters & Paratha',
  },
  {
    id: 'special-paratha-roll',
    nameEn: 'Special Paratha Roll',
    nameUr: 'اسپیشل پراٹھا رول',
    categoryId: 'platters-rolls',
    price: 350,
    descriptionEn: 'Student Shawarma special loaded paratha roll with a premium combination of chicken chunks, sauces, and spices.',
    descriptionUr: 'سٹوڈنٹ اسپیشل رول، فل چکن اور خصوصی چٹخارے دار مصالحہ کے ساتھ۔',
    image: '/images/products/special-paratha-roll.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '350/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Right Bottom - Platters & Paratha',
  },

  // BURGERS (Left top column)
  {
    id: 'zinger-burger',
    nameEn: 'Zinger Burger',
    nameUr: 'زنگر برگر',
    categoryId: 'burgers',
    price: 280,
    descriptionEn: 'Crispy fried spicy chicken breast fillet topped with fresh lettuce and rich creamy mayo in a toasted sesame bun.',
    descriptionUr: 'کرسپی فرائیڈ چکن فلے، تازہ سلاد پتہ اور مایونیز تل والے برگر بن میں۔',
    image: '/images/products/zinger-burger.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '280/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Top - Burgers',
  },
  {
    id: 'chicken-burger',
    nameEn: 'Chicken Burger',
    nameUr: 'چکن برگر',
    categoryId: 'burgers',
    price: 230,
    descriptionEn: 'Seasoned minced chicken patty grilled to perfection with onions and house sauce.',
    descriptionUr: 'لذیذ گرلڈ چکن پیٹی برگر روایتی مصالحہ دار ساس کے ساتھ۔',
    image: '/images/products/chicken-burger.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '230/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Top - Burgers',
  },
  {
    id: 'student-special-chicken-burger',
    nameEn: 'Student Special Chicken Burger',
    nameUr: 'سٹوڈنٹ اسپیشل چکن برگر',
    categoryId: 'burgers',
    price: 260,
    descriptionEn: 'Our signature loaded chicken burger with double sauce, fried egg/cheese layering, and extra crispiness.',
    descriptionUr: 'سٹوڈنٹ فاسٹ فوڈ کا اسپیشل چکن برگر، خاص ذائقہ اور مصالحہ۔',
    image: '/images/products/student-special-chicken-burger.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '260/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Top - Burgers',
  },
  {
    id: 'chicken-tikka-burger',
    nameEn: 'Chicken Tikka Burger',
    nameUr: 'چکن تکہ برگر',
    categoryId: 'burgers',
    price: 250,
    descriptionEn: 'Chargrilled BBQ chicken tikka chunks packed inside a soft toasted bun with spicy yogurt sauce.',
    descriptionUr: 'باربی کیو چکن تکہ کا لاجواب ذائقہ برگر بن میں۔',
    image: '/images/products/chicken-tikka-burger.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '250/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Top - Burgers',
  },
  {
    id: 'anda-shami-burger',
    nameEn: 'Anda Shami Burger',
    nameUr: 'انڈہ شامی برگر',
    categoryId: 'burgers',
    price: 150,
    descriptionEn: 'Authentic Pakistani street-style burger featuring a seasoned shami patty topped with a fresh fried egg and onion rings.',
    descriptionUr: 'روایتی دیسی شامی کباب اور تلے ہوئے انڈے کا مشہور لاہوری برگر۔',
    image: '/images/products/anda-shami-burger.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '150/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Top - Burgers',
  },

  // CHICKEN & SNACKS (Left middle column)
  {
    id: 'chicken-drumstick',
    nameEn: 'Chicken Drumstick (1 pc)',
    nameUr: 'چکن ڈرم اسٹک',
    categoryId: 'chicken-snacks',
    price: 120,
    descriptionEn: 'Golden crispy southern-fried chicken drumstick, crunchy on the outside, juicy on the inside.',
    descriptionUr: 'کرسپی فرائیڈ چکن ڈرم اسٹک (1 عدد)۔',
    image: '/images/products/chicken-drumstick.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '120/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Middle - Snacks',
  },
  {
    id: 'zinger-wrap',
    nameEn: 'Zinger Wrap',
    nameUr: 'زنگر Wrap',
    categoryId: 'chicken-snacks',
    price: 350,
    descriptionEn: 'Crispy zinger chicken strips, lettuce, and creamy pepper sauce wrapped tightly in a toasted flour tortilla.',
    descriptionUr: 'کرنچی زنگر چکن اور سپائسی مایو ٹارٹیلا ریپ میں۔',
    image: '/images/products/zinger-wrap.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '350/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Middle - Snacks',
  },
  {
    id: 'wings-5-pcs',
    nameEn: 'Wings (5 Pieces)',
    nameUr: 'ونگز پیس 5',
    categoryId: 'chicken-snacks',
    price: 300,
    descriptionEn: 'Five pieces of crispy golden breaded chicken wings served with dipping sauce.',
    descriptionUr: 'کرسپی فرائیڈ چکن ونگز 5 عدد۔',
    image: '/images/products/wings-5-pcs.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '300/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Middle - Snacks',
  },
  {
    id: 'wings-10-pcs',
    nameEn: 'Wings (10 Pieces)',
    nameUr: 'ونگز پیس 10',
    categoryId: 'chicken-snacks',
    price: 590,
    descriptionEn: 'Ten pieces of golden crispy chicken wings, perfect for sharing.',
    descriptionUr: 'کرسپی فرائیڈ چکن ونگز 10 عدد، فیملی اور دوستوں کے لیے۔',
    image: '/images/products/wings-10-pcs.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '590/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Middle - Snacks',
  },

  // SANDWICHES (Left 3rd column)
  {
    id: 'club-sandwich',
    nameEn: 'Club Sandwich',
    nameUr: 'کلب سینڈوچ',
    categoryId: 'sandwiches',
    price: 270,
    descriptionEn: 'Classic triple-layered toasted sandwich loaded with shredded chicken, boiled egg slices, cucumber, and creamy spread.',
    descriptionUr: 'کلاسک تھری لیئر ٹوسٹڈ کلب سینڈوچ چکن، انڈہ اور مایو کے ساتھ۔',
    image: '/images/products/club-sandwich.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '270/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left 3rd - Sandwiches',
  },
  {
    id: 'chicken-tikka-sandwich',
    nameEn: 'Chicken Tikka Sandwich',
    nameUr: 'چکن تکہ سینڈوچ',
    categoryId: 'sandwiches',
    price: 290,
    descriptionEn: 'Toasted golden bread sandwiches stuffed with smoky spiced chicken tikka pieces and tangy sauce.',
    descriptionUr: 'باربی کیو چکن تکہ سے بھرا گرلڈ ٹوسٹڈ سینڈوچ۔',
    image: '/images/products/chicken-tikka-sandwich.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '290/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left 3rd - Sandwiches',
  },
  {
    id: 'zinger-sandwich',
    nameEn: 'Zinger Sandwich',
    nameUr: 'زنگر سینڈوچ',
    categoryId: 'sandwiches',
    price: 300,
    descriptionEn: 'Crispy fried zinger chicken fillet nestled between toasted bread slices with crisp lettuce and sauce.',
    descriptionUr: 'کرسپی فرائیڈ زنگر چکن اور مایونیز سینڈوچ۔',
    image: '/images/products/zinger-sandwich.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '300/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left 3rd - Sandwiches',
  },
  {
    id: 'student-special-sandwich',
    nameEn: 'Student Special Sandwich',
    nameUr: 'سٹوڈنٹ اسپیشل سینڈوچ',
    categoryId: 'sandwiches',
    price: 350,
    descriptionEn: 'Deluxe loaded sandwich with double meat filling, melted cheese layer, and secret house seasoning.',
    descriptionUr: 'سٹوڈنٹ کا خاص سینڈوچ، ڈبل چکن فلنگ اور چیز سے بھرپور۔',
    image: '/images/products/student-special-sandwich.webp',
    isAvailable: true,
    isFeatured: true,
    originalPriceFormat: '350/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left 3rd - Sandwiches',
  },

  // EXTRAS & ADD-ONS (Left bottom column)
  {
    id: 'cheese-slice',
    nameEn: 'Cheese Slice',
    nameUr: 'چیز سلائس',
    categoryId: 'addons',
    price: 60,
    descriptionEn: 'Add an extra melted cheddar cheese slice to your shawarma, burger, or sandwich.',
    descriptionUr: 'شوارما یا برگر کے لیے اضافی چیز سلائس۔',
    image: '/images/products/cheese-slice.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '60/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Bottom - Extras',
  },
  {
    id: 'extra-mayo',
    nameEn: 'Extra Mayonnaise',
    nameUr: 'ایکسٹرا مایونیز',
    categoryId: 'addons',
    price: 30,
    descriptionEn: 'A cup of rich, creamy house garlic mayonnaise dip.',
    descriptionUr: 'اضافی گھریلو گارلک مایونیز ساس۔',
    image: '/images/products/extra-mayo.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '30/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Bottom - Extras',
  },
  {
    id: 'extra-bread',
    nameEn: 'Extra Bread / Pita',
    nameUr: 'ایکسٹرا بریڈ',
    categoryId: 'addons',
    price: 30,
    descriptionEn: 'An extra piece of warm, freshly made shawarma pita bread.',
    descriptionUr: 'اضافی تازہ شوارما پیٹا بریڈ۔',
    image: '/images/products/extra-bread.webp',
    isAvailable: true,
    isFeatured: false,
    originalPriceFormat: '30/- روپے',
    verifiedFromMenu: true,
    originalMenuSection: 'Left Bottom - Extras',
  },
];

export const initialDeals: Deal[] = [
  {
    id: 'deal-3',
    dealNumber: 3,
    nameEn: 'Student Deal 3',
    nameUr: 'ڈیل 3',
    price: 250,
    originalPriceFormat: '250/-',
    image: '/images/deals/deal-3.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Regular Shawarma + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Regular Shawarma', nameUr: '1 ریگولر شوارما', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-4',
    dealNumber: 4,
    nameEn: 'Student Deal 4',
    nameUr: 'ڈیل 4',
    price: 300,
    originalPriceFormat: '300/-',
    image: '/images/deals/deal-4.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Special Shawarma + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Special Shawarma', nameUr: '1 اسپیشل شوارما', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-5',
    dealNumber: 5,
    nameEn: 'Student Deal 5',
    nameUr: 'ڈیل 5',
    price: 400,
    originalPriceFormat: '400/-',
    image: '/images/deals/deal-5.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Zinger Paratha Roll + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Zinger Paratha Roll', nameUr: '1 زنگر پراٹھا رول', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-6',
    dealNumber: 6,
    nameEn: 'Student Deal 6',
    nameUr: 'ڈیل 6',
    price: 350,
    originalPriceFormat: '350/-',
    image: '/images/deals/deal-6.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Zinger Shawarma + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Zinger Shawarma', nameUr: '1 زنگر شوارما', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-7',
    dealNumber: 7,
    nameEn: 'Student Deal 7',
    nameUr: 'ڈیل 7',
    price: 250,
    originalPriceFormat: '250/-',
    image: '/images/deals/deal-7.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Shami Burger + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Shami Burger', nameUr: '1 شامی برگر', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-8',
    dealNumber: 8,
    nameEn: 'Student Deal 8',
    nameUr: 'ڈیل 8',
    price: 300,
    originalPriceFormat: '300/-',
    image: '/images/deals/deal-8.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Chicken Patty Burger + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Chicken Patty Burger', nameUr: '1 چکن پیٹی برگر', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-9',
    dealNumber: 9,
    nameEn: 'Student Deal 9',
    nameUr: 'ڈیل 9',
    price: 350,
    originalPriceFormat: '350/-',
    image: '/images/deals/deal-9.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Chicken Burger + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Chicken Burger', nameUr: '1 چکن برگر', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-10',
    dealNumber: 10,
    nameEn: 'Student Deal 10',
    nameUr: 'ڈیل 10',
    price: 400,
    originalPriceFormat: '400/-',
    image: '/images/deals/deal-10.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Chicken Sandwich + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Chicken Sandwich', nameUr: '1 چکن سینڈوچ', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-11',
    dealNumber: 11,
    nameEn: 'Student Deal 11',
    nameUr: 'ڈیل 11',
    price: 350,
    originalPriceFormat: '350/-',
    image: '/images/deals/deal-11.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Club Sandwich + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Club Sandwich', nameUr: '1 کلب سینڈوچ', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-12',
    dealNumber: 12,
    nameEn: 'Student Deal 12',
    nameUr: 'ڈیل 12',
    price: 400,
    originalPriceFormat: '400/-',
    image: '/images/deals/deal-12.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Chicken Tikka Sandwich + Crispy French Fries + 1 Regular Drink',
    components: [
      { nameEn: 'Chicken Tikka Sandwich', nameUr: '1 چکن تکہ سینڈوچ', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: 'Regular Cold Drink', nameUr: '1 ریگولر بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-13',
    dealNumber: 13,
    nameEn: 'Student Family Deal 13',
    nameUr: 'فیملی ڈیل 13',
    price: 2100,
    originalPriceFormat: '2100/-',
    image: '/images/deals/deal-13.webp',
    isAvailable: true,
    isFamilyDeal: true,
    verifiedFromMenu: true,
    descriptionEn: '2 Regular Shawarma + 1 Shami Burger + 1 Student Special Chicken Burger + 1 Chicken Patty Burger + 2 Zinger Burgers + 1 Chicken Sandwich + French Fries + 1.5 Liter Bottle',
    components: [
      { nameEn: 'Regular Shawarma', nameUr: '2 ریگولر شوارما', quantity: 2 },
      { nameEn: 'Shami Burger', nameUr: '1 شامی برگر', quantity: 1 },
      { nameEn: 'Student Special Chicken Burger', nameUr: '1 سٹوڈنٹ اسپیشل چکن برگر', quantity: 1 },
      { nameEn: 'Chicken Patty Burger', nameUr: '1 چکن پیٹی برگر', quantity: 1 },
      { nameEn: 'Zinger Burgers', nameUr: '2 زنگر برگر', quantity: 2 },
      { nameEn: 'Chicken Sandwich', nameUr: '1 چکن سینڈوچ', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: '1.5 Liter Cold Drink Bottle', nameUr: '1.5 Liter بوتل', quantity: 1 },
    ],
  },
  {
    id: 'deal-14',
    dealNumber: 14,
    nameEn: 'Student Deal 14 (Combo Feast)',
    nameUr: 'ڈیل 14',
    price: 800,
    originalPriceFormat: '800/-',
    image: '/images/deals/deal-14.webp',
    isAvailable: true,
    verifiedFromMenu: true,
    descriptionEn: '1 Regular Shawarma + 1 Shami Burger + 1 Zinger Burger + Crispy French Fries + 1 Liter Bottle',
    components: [
      { nameEn: 'Regular Shawarma', nameUr: '1 ریگولر شوارما', quantity: 1 },
      { nameEn: 'Shami Burger', nameUr: '1 شامی برگر', quantity: 1 },
      { nameEn: 'Zinger Burger', nameUr: '1 زنگر برگر', quantity: 1 },
      { nameEn: 'French Fries', nameUr: 'فرائز', quantity: 1 },
      { nameEn: '1 Liter Cold Drink Bottle', nameUr: '1 Liter بوتل', quantity: 1 },
    ],
  },
];

export const initialDiningTables: DiningTable[] = [
  { id: 'T01', label: 'Table 1', seats: 4, isActive: true },
  { id: 'T02', label: 'Table 2', seats: 4, isActive: true },
  { id: 'T03', label: 'Table 3', seats: 2, isActive: true },
  { id: 'T04', label: 'Table 4', seats: 6, isActive: true },
  { id: 'T05', label: 'Table 5', seats: 4, isActive: true },
  { id: 'T06', label: 'Table 6 (Family Hall)', seats: 8, isActive: true },
];

export const initialBusinessSettings: BusinessSettings = {
  restaurantName: 'Student Shawarma & Fast Food',
  urduName: 'سٹوڈنٹ شوارما اینڈ فاسٹ فوڈ',
  tagline: 'Best Shawarma, Burgers & Student Deals in Lahore',
  phoneCandidate: '0309-4222283',
  whatsappNumberFormatted: '923094222283',
  isWhatsAppConfirmedByOwner: false, // Flagged pending owner confirmation per instructions
  address: 'Shalimar Link Road, Ramgarh, Lahore, Pakistan',
  city: 'Lahore',
  googleMapsUrl: 'https://maps.google.com/?q=Shalimar+Link+Road+Lahore',
  facebookUrl: 'https://www.facebook.com/p/Student-pizza-Fastfood-100089295146903/',
  openingHoursFormatted: 'Mon – Sat: 1:00 PM – 1:00 AM (Sunday Off)',
  isSundayOff: true,
  deliveryCharges: 100, // PKR
  minimumOrder: 250, // PKR
  announcementText: '🔥 Fresh & Piping Hot! Free fries dip on all orders above Rs. 1000. Dine-in & Takeaway available daily (Sunday Off).',
  isAnnouncementActive: true,
  currencySymbol: 'Rs.',
  dineInEnabled: true,
  takeawayEnabled: true,
  deliveryEnabled: true,
};
